// Authentication
export const LOGIN_REQUEST = '@@AUTH/LOGIN_REQUEST';
export const LOGIN_FAILURE = '@@AUTH/LOGIN_FAILURE';
export const LOGIN_SUCCESS = '@@AUTH/LOGIN_SUCCESS';

export const LOGOUT_REQUEST = '@@AUTH/LOGOUT_REQUEST';
export const LOGOUT_FAILURE = '@@AUTH/LOGOUT_FAILURE';
export const LOGOUT_SUCCESS = '@@AUTH/LOGOUT_SUCCESS';

export const SIGNUP_REQUEST = '@@AUTH/SIGNUP_REQUEST';
export const SIGNUP_FAILURE = '@@AUTH/SIGNUP_FAILURE';
export const SIGNUP_SUCCESS = '@@AUTH/SIGNUP_SUCCESS';

// Post
export const SET_POSTS_REQUEST = '@@POST/SET_POSTS_REQUEST';
export const SET_POSTS_FAILURE = '@@POST/SET_POSTS_FAILURE';
export const SET_POSTS_SUCCESS = '@@POST/SET_POSTS_SUCCESS';

export const ADD_POST_REQUEST = '@@POST/ADD_POST_REQUEST';
export const ADD_POST_FAILURE = '@@POST/ADD_POST_FAILURE';
export const ADD_POST_SUCCESS = '@@POST/ADD_POST_SUCCESS';

export const REMOVE_POST_REQUEST = '@@POST/REMOVE_POST_REQUEST';
export const REMOVE_POST_FAILURE = '@@POST/REMOVE_POST_FAILURE';
export const REMOVE_POST_SUCCESS = '@@POST/REMOVE_POST_SUCCESS';

// Comment
export const ADD_COMMENT_REQUEST = '@@COMMENT/ADD_COMMENT_REQUEST';
export const ADD_COMMENT_FAILURE = '@@COMMENT/ADD_COMMENT_FAILURE';
export const ADD_COMMENT_SUCCESS = '@@COMMENT/ADD_COMMENT_SUCCESS';

export const REMOVE_COMMENT_REQUEST = '@@COMMENT/REMOVE_COMMENT_REQUEST';
export const REMOVE_COMMENT_FAILURE = '@@COMMENT/REMOVE_COMMENT_FAILURE';
export const REMOVE_COMMENT_SUCCESS = '@@COMMENT/REMOVE_COMMENT_SUCCESS';
